// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Splitwise_Backend.Models;
using System;

namespace Splitwise_Backend.Migrations
{
    [DbContext(typeof(Splitwise_BackendContext))]
    [Migration("20180831074931_User")]
    partial class User
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Splitwise_Backend.Models.Picture", b =>
                {
                    b.Property<int>("Picture_Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Large");

                    b.Property<string>("Medium");

                    b.Property<string>("Small");

                    b.Property<int?>("UserId");

                    b.HasKey("Picture_Id");

                    b.HasIndex("UserId");

                    b.ToTable("Picture");
                });

            modelBuilder.Entity("Splitwise_Backend.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Registration");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Splitwise_Backend.Models.Picture", b =>
                {
                    b.HasOne("Splitwise_Backend.Models.User")
                        .WithMany("Picture")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
